from langgraph.graph import StateGraph,END,START,MessagesState
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.documents import Document
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings,ChatOpenAI
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader
from dotenv import load_dotenv

from pathlib import Path

load_dotenv()

base_dir = Path(__file__).resolve().parent
documents_dir = base_dir / "documents"
pdf_path = documents_dir / "evs_oil_price_shock.pdf"

# 1. Load the PDF
loader = PyPDFLoader(str(pdf_path))
docs = loader.load()
print(f"Loaded {len(docs)} pages from the PDF.")


# 2. Split documents into chunks
splitter = RecursiveCharacterTextSplitter(chunk_size=900,chunk_overlap=100)
chunks = splitter.split_documents(docs)
print(f"\nSplit into {len(chunks)} chunks.")

# 3. Embeddings & Vector Store 
embedding = OpenAIEmbeddings(model="text-embedding-3-large")
vector_store = Chroma(
    collection_name = "rag_base",
    embedding_function=embedding,
)
vector_store.add_documents(documents=chunks)
print("\nVector store created successfully.")

# 4. Create Retriever
retriever = vector_store.as_retriever(search_type="similarity",search_kwargs={"k":4})
print("\nRetriever created successfully.")


# 5.Graph State
class AgenticRAGState(MessagesState):
    query:str
    retrieved_docs: list[Document] # All documents returned from tools before filtering eg. [doc1,doc2,doc3,doc4]
    context:str                   # Combined text from relevant_docs used for answer generation
    response:str                  # Final answer generated by the LLM 
    
# 6.initialize llm
llm = ChatOpenAI(model="gpt-5-mini")

#======1st NODE ======
# retrieves relevant docs from the vector store
def retrieve_node(state:AgenticRAGState)-> dict:
    retrieved_docs = retriever.invoke(state["query"])
    context = "\n\n".join([d.page_content for d in retrieved_docs]) # joining each  string onto one paragraph
    print(f"\nRetrieved {len(retrieved_docs)} chunks.\n")
    return {
        "retrieved_docs" : retrieved_docs,
        "context" : context
    }

#======2nd NODE ======
#generate a response using the retrieved context
def generate_node(state:AgenticRAGState)-> dict:
    query =  state["query"] #Pulling from State
    context = state.get("context","")
    prompt_template = ChatPromptTemplate.from_messages(
        [
            ("system", "Answer the question using only the context below. \n\nContext:\n{context}"),
            ("human","Question: {query}")
        ]
    ) 
    response = (prompt_template | llm).invoke({"context":context, "query" : query})
    return {"response": response.content}
    
    

# build the RAG graph 
g = StateGraph(AgenticRAGState)

# add nodes to the graph
g.add_node("retrieve",retrieve_node)
g.add_node("generate",generate_node)

# Edges
g.add_edge(START, "retrieve")
g.add_edge("retrieve","generate")
g.add_edge("generate", END)

graph = g.compile()

result = graph.invoke(
    {
        "query":"How will EVs impact on oil demand in the next decade?",
        
        # Required by MessagesState (inherited by AgenticRAGState).
        # Holds the conversation history for multi-turn chat.
        "messages":[],
        
    }
)

print("\n===== FINAL RESULT =====\n")
print(result["response"])


# -----------------------------
# Debug / inspection output (clean + complete)
# -----------------------------
print("\n=== RETRIEVED DOCUMENTS ===")
for i, doc in enumerate(result["retrieved_docs"], 1):
    source = doc.metadata.get("source", "unknown")
    page = doc.metadata.get("page", "?")
    snippet = doc.page_content[:500].replace("\n", " ")
    print(f"[{i}] Source: {source} | Page: {page}")
    print(f"    {snippet}...")
    
print("\n=====RETRIEVED CONTEXT===") 
print(result["context"])