import os
import operator
from pathlib import Path
from typing import Annotated, Literal
from pydantic import BaseModel
from tavily import TavilyClient
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_core.documents import Document
from langgraph.graph import StateGraph, START, END, MessagesState
from langgraph.prebuilt import ToolNode
from dotenv import load_dotenv
load_dotenv()

base_dir = Path(__file__).resolve().parent
documents_dir = base_dir / "documents"
pdf_path = documents_dir / "evs_oil_price_shock.pdf"

# 1. Load the PDF
loader = PyPDFLoader(str(pdf_path))
docs = loader.load()
print(f"Loaded {len(docs)} pages from the PDF.")

# 2. Split documents into chunks
splitter = RecursiveCharacterTextSplitter(chunk_size=900,chunk_overlap=150)
chunks = splitter.split_documents(docs)
print(f"\nSplit into {len(chunks)} chunks.")

# 3. Embeddings & Vector Store
embedding = OpenAIEmbeddings(model="text-embedding-3-large")
vector_store = Chroma(
    collection_name="rag_tool_use",
    embedding_function=embedding,
)
vector_store.add_documents(documents=chunks)
print("\nVector store created successfully.")

# 4. initializing model
llm = ChatOpenAI(model="gpt-5-mini",temperature=0)
agent_llm = ChatOpenAI(model="gpt-4o-mini")

# 6. State Graph definition - shared memory of the graph.
class AgenticRAGState(MessagesState):
    query:str
    retrieved_docs:Annotated[list[Document], operator.add] # # Store retrieved documents and append new docs instead of replacing old ones
    context:Annotated[str,operator.add] # "PDF result" + "Web result"
    generation:str
    needs_retrieval:bool
    
    
# ----------------1st TOOL -----------------
# Register this function as a tool and return both text and raw documents
@tool(response_format="content_and_artifact") # content  → text for LLM, artifact → raw objects for workflow
def vector_store_search(query:str,k:int=3):
    """Search the vector store for relevant document passages.
    Adjust k (default 3) to retrieve more or fewer passages."""
    
    # Search vector database and return top-k matching chunks
    retriever = vector_store.as_retriever(search_type = "similarity",search_kwargs={"k":k})
    docs = retriever.invoke(query) # Perform Search | # Retrieve the most relevant document chunks for the query
    
    
    # Merge retrieved chunks into a single text context for the LLM
    context = "\n\n## Vector Store Results\n\n" + "\n\n".join([d.page_content for d in docs]) # merge into one context string for llm
    return context,docs # return text as content for LLM and raw docs as artifacts


# ----------------2nd TOOL -----------------
@tool(response_format="content_and_artifact")
def web_search(query:str, max_results:int=3):
    """Search the web for current or real-time information.
    Adjust max_results (default 3) to control how many results are returned."""
    
    client = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])
    response = client.search(query=query,max_results=max_results)
    
    # Convert Tavily search results into LangChain Document objects and vector search tool returns so web tool should return the same format
    docs = [
        Document(
            page_content= r["content"],
            metadata = {"source": r["url"],"title":r.get("title","")}
        )
        for r in response.get("results",[])
    ]
    content = "\n\n## web Search Results\n\n" + "\n\n".join([d.page_content for d in docs])
    return content,docs
    

# Register all available tools that the agent can use
tools = [vector_store_search,web_search]
agent_llm_with_tools = agent_llm.bind_tools(tools) # LLM + Tools = Tool-Calling Agent
#======1st NODE ( LangGraph execution node)======
# 8.a tool_node — Executes tool calls generated by the LLM and returns ToolMessage outputs
tool_node = ToolNode(tools) # a node that can execute any of the defined tools


#======2nd NODE (Router node)======
# 7.a structure output schema for the routing decision for llm
class RouteDecision(BaseModel):
    need_retrieval:bool
 
# 7.b route_question node - it classifies whether the query needs documents for retrieval or not.
def route_question_node(state:AgenticRAGState) -> dict:
    
    prompt_template = ChatPromptTemplate.from_messages([
        ("system", "Classify whether the following question requires retrieving information from a specialized document or the web, or can be answered from your own general knowledge."),
        ("human", "Question:{query}")
    ])
    # Convert LLM into a structured classifier that outputs a boolean decision
    chain = prompt_template | llm.with_structured_output(RouteDecision)
    decision = chain.invoke({"query":state["query"]})
    
    # Store routing decision in shared graph state
    return {"needs_retrieval":decision.need_retrieval} 
   
 
AGENT_SYSTEM_PROMPT = (
    "You are a retrieval agent with access to two tools:\n\n"
    "1. vector_store_search — use this for questions that can be answered from the internal document: "
    "a technical report titled 'Will EVs Dampen the Oil Price Shock?' covering EV adoption trajectories, "
    "oil demand displacement scenarios, fleet turnover dynamics, battery cost trends, OPEC+ supply behavior, "
    "and energy price volatility projections through 2050. "
    "Use this tool whenever the query references the report, its findings, its projections, or any topic "
    "that would plausibly appear in a domain-specific EV/oil-market research document. "
    "You may increase k beyond the default if broader coverage of the document is needed.\n\n"
    "2. web_search — use this for current or real-time information not covered by the document, such as "
    "recent market data, news, or statistics from 2024 onward. "
    "Always rephrase the query into a concise, keyword-optimized web search string before calling this tool.\n\n"
    "You may call one tool, both tools, or no tool depending on what the query requires. "
    "When both document knowledge and current data are relevant, call both tools."
)

#======3rd NODE======
# 8.agent node — decides which tool(s) to call based on the query | Think → Decide → Possibly call tools
def agent_node(state:AgenticRAGState)->dict:
     # Get full conversation history from state
    messages = state["messages"]
    
    # Initialize conversation with system instructions and user query
    if not messages:
        messages = [SystemMessage(content=AGENT_SYSTEM_PROMPT),
                    HumanMessage(content=state["query"])]

# LLM processes conversation and may decide to call tools or answer directly
    response = agent_llm_with_tools.invoke(messages)

    return {"messages": [response]}


#======4th NODE======
# 9.collect_tool_output node — drains ToolMessages into state fields | Take tool results → extract useful data → store in state
def collect_tool_output_node(state: AgenticRAGState) ->dict:
    
    # Extract only ToolMessage outputs from conversation history
    # isinstance() checks an object’s type so you can safely filter and use only the data you need.
    tool_message = [m for m in state["messages"] if isinstance(m,ToolMessage)] 
    all_docs, context_parts = [],[]
    # all_docs → raw retrieved documents
    # context_parts → text content for LLM
    # when tool returns content + artifact → LangGraph wraps them in ToolMessage
    
    # ToolMessage(
    # content="some text",
    # artifact=[Document, Document])

    
    for msg in tool_message:
        context_parts.append(msg.content) # Collect human-readable tool output text | append - returned nested lists
        all_docs.extend(msg.artifact)  # # Collect raw documents from tool outputs | extend - returned single combined list
    return{
        "context": "\n\n".join(context_parts),  # Combine all tool outputs into a single context string for LLM
        "retrieved_docs": all_docs # Store all raw documents retrieved from tools
    }
        
#======5th NODE======
# 10.generate_node - produce the final answer with o without a retrieve context
def generate_node(state: AgenticRAGState)->dict:
    
    query = state["query"]
    context = state["context"]  # information from tools (PDF + web)

    if context:
        prompt_template = ChatPromptTemplate.from_messages([
            ("system","answer the question using only the context below. \n\nContext:\n{context}"),
            ("human","Question:{query}")
        ])
        # Generate answer using retrieved context (RAG mode)
        response = (prompt_template | llm).invoke({"query": query, "context": context})
    else:
        prompt_template = ChatPromptTemplate.from_messages([
            ("system","answer the following question from your general knowledge."),
            ("human","Question:{query}")
        ])
        # Generate answer without external context
        response = (prompt_template | llm).invoke({"query": query})
        
    # Store final answer in graph state
    return {"generation": response.content}  
        
# ======= 11. The conditional ROUTER (routing function) =====   
def route_after_classification(state: AgenticRAGState)->Literal["agent_node","generate_node"]:
     # Decide whether to use agent tools or go directly to final generation
    return "agent_node" if state["needs_retrieval"] else "generate_node"

def route_after_agent(state:AgenticRAGState) -> Literal["tool_node","collect_tool_output_node"]:
    return "tool_node" if state["messages"][-1].tool_calls else "collect_tool_output_node"
    # If tool calls exist → execute tool; otherwise → process results
    
     
# 12. Graph defination
g = StateGraph(AgenticRAGState)
g.add_node("route_question_node",route_question_node)
g.add_node("agent_node",agent_node)
g.add_node("collect_tool_output_node",collect_tool_output_node)
g.add_node("generate_node",generate_node)
g.add_node("tool_node",tool_node)

# 12. edges
g.add_edge(START,"route_question_node")
g.add_conditional_edges("route_question_node",route_after_classification)
g.add_conditional_edges("agent_node",route_after_agent)
g.add_edge("tool_node","agent_node")
g.add_edge("collect_tool_output_node", "generate_node")
g.add_edge("generate_node",END)

graph = g.compile()
save_path = base_dir / "agentic_rag_step03.png"
png_data = graph.get_graph().draw_mermaid_png()
with open(save_path, "wb") as f:
    f.write(png_data)
print("Graph saved successfully!")



# Case 1: vector store only — domain-specific question about the PDF
query_vs = "According to the report, how will the adoption of electric vehicles impact oil demand?"
result_vs = graph.invoke({"query": query_vs, "messages": [], "retrieved_docs": [], "context": ""})

print("=== CASE 1: Vector Store Only ===")
print(f"needs_retrieval : {result_vs['needs_retrieval']}")
print(f"retrieved_docs  : {len(result_vs.get('retrieved_docs') or [])} docs")
print(f"context preview : {result_vs.get('context', '')[:120]}...")
print(f"\nGeneration:\n{result_vs['generation']}")

print(result_vs["context"])


# Case 2: web search only — current information not in the PDF
query_web = "What is the current temperature in Sydney?"
result_web = graph.invoke({"query": query_web, "messages": [], "retrieved_docs": [], "context": ""})

print(f"\n=== CASE 2: Web Search Only ===")
print(f"needs_retrieval : {result_web['needs_retrieval']}")
print(f"retrieved_docs  : {len(result_web.get('retrieved_docs') or [])} docs")
print(f"context preview : {result_web.get('context', '')[:120]}...")
print(f"\nGeneration:\n{result_web['generation']}")



# Case 3: both tools — requires document context AND current web data
query_both = "Compare what the EV report projects for 2030 oil demand and also tell me about the weather in melbourne"
result_both = graph.invoke({"query": query_both, "messages": [], "retrieved_docs": [], "context": ""})

print("\n=== CASE 3: Both Tools ===")
print(f"needs_retrieval : {result_both['needs_retrieval']}")
print(f"retrieved_docs  : {len(result_both.get('retrieved_docs') or [])} docs")
print(f"context preview : {result_both.get('context', '')[:120]}...")
print(f"\nGeneration:\n{result_both['generation']}")

print(result_both["context"])

# Case 4: no retrieval — answerable from general knowledge
query_none = "Explain the difference between kinetic energy and potential energy."
result_none = graph.invoke({"query": query_none, "messages": [], "retrieved_docs": [], "context": ""})

print("\n=== CASE 4: No Retrieval ===")
print(f"needs_retrieval : {result_none['needs_retrieval']}")
print(f"retrieved_docs  : {len(result_none.get('retrieved_docs') or [])} docs")
print(f"context preview : {result_none.get('context', '') or '(none)'}")
print(f"\nGeneration:\n{result_none['generation']}")

result_both["messages"][0].tool_calls
    

    


    


