import os
import operator
from pathlib import Path
from typing import Annotated, Literal
from pydantic import BaseModel
from tavily import TavilyClient
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_core.documents import Document
from langgraph.graph import StateGraph, START, END, MessagesState
from langgraph.prebuilt import ToolNode
from dotenv import load_dotenv
load_dotenv()

base_dir = Path(__file__).resolve().parent
documents_dir = base_dir / "documents"
pdf_path = documents_dir / "evs_oil_price_shock.pdf"

# 1. Load the PDF
loader = PyPDFLoader(str(pdf_path))
docs = loader.load()
print(f"Loaded {len(docs)} pages from the PDF.")

# 2. Split documents into chunks
splitter = RecursiveCharacterTextSplitter(chunk_size=900,chunk_overlap=150)
chunks = splitter.split_documents(docs)
print(f"\nSplit into {len(chunks)} chunks.")

# 3. Embeddings & Vector Store
embedding = OpenAIEmbeddings(model="text-embedding-3-large")
vector_store = Chroma(
    collection_name="rag_tool_use",
    embedding_function=embedding,
)
vector_store.add_documents(documents=chunks)
print("\nVector store created successfully.")

# 4. initializing model
llm = ChatOpenAI(model="gpt-5-mini",temperature=0)
agent_llm = ChatOpenAI(model="gpt-4o-mini")

# 6. State Graph definition - shared memory of the graph.
class AgenticRAGState(MessagesState):
    query:str
    retrieved_docs: list[Document]
    relevant_docs: list[Document]
    context:str 
    generation:str
    needs_retrieval:bool
    retrieval_count: int       # incremented after each tool-call round
    max_retrieval_steps: int   # cap on tool-call rounds before forcing generate
    is_relevant:bool
    rewritten_query: str
    rewrite_count:int
    needs_decomposition: bool
    
    
# ----------------1st TOOL -----------------
# Register this function as a tool and return both text and raw documents
@tool(response_format="content_and_artifact") # content  → text for LLM, artifact → raw objects for workflow
def vector_store_search(query:str,k:int=3):
    """Search the vector store for relevant document passages.
    Adjust k (default 3) to retrieve more or fewer passages."""
    
    # Search vector database and return top-k matching chunks
    retriever = vector_store.as_retriever(search_type = "similarity",search_kwargs={"k":k})
    docs = retriever.invoke(query) # Perform Search | # Retrieve the most relevant document chunks for the query
    
    # Merge retrieved chunks into a single text context for the LLM
    context = "\n\n## Vector Store Results\n\n" + "\n\n".join([d.page_content for d in docs]) # merge into one context string for llm
    return context,docs # return text as content for LLM and raw docs as artifacts

    
# ----------------2nd TOOL -----------------
@tool(response_format="content_and_artifact")
def web_search(query:str, max_results:int=3):
    """Search the web for current or real-time information.
    Adjust max_results (default 3) to control how many results are returned."""
    
    client = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])
    response = client.search(query=query,max_results=max_results)
    
    # Convert Tavily search results into LangChain Document objects and vector search tool returns so web tool should return the same format
    docs = [
        Document(
            page_content= r["content"],
            metadata = {"source": r["url"],"title":r.get("title","")}
        )
        for r in response.get("results",[])
    ]
    content = "\n\n## web Search Results\n\n" + "\n\n".join([d.page_content for d in docs])
    return content,docs

# Register all available tools that the agent can use
tools = [vector_store_search,web_search]
agent_llm_with_tools = agent_llm.bind_tools(tools) # LLM + Tools = Tool-Calling Agent
#======1st NODE ( LangGraph execution node)======
# 8.a tool_node — Executes tool calls generated by the LLM and returns ToolMessage outputs
tool_node = ToolNode(tools) # a node that can execute any of the defined tools

#============2nd NODE ======
class DecompositionDecision(BaseModel):
    needs_decomposition: bool
    sub_queries: list[str]  # empty list when needs_decomposition=False

# check_decompositio_node - 
def check_decompositio_node(state: AgenticRAGState) -> dict:
    prompt_template = ChatPromptTemplate.from_messages([
        (
            "system",
            "You are a query analysis assistant. Determine if the user's question asks for "
            "multiple distinct pieces of information that each require separate retrieval. "
            "If yes, needs_decomposition should be True. "
            "If the question is simple or self-contained, needs_decomposition should be False."
        ),
        ("human", "{query}"),
    ])
    
    chain = prompt_template | llm.with_structured_output(DecompositionDecision)
    result = chain.invoke({"query": state["query"]})
    
    return {"needs_decomposition": result.needs_decomposition}


#===========3rd NODE ======
#decompose_query_node - it decomposes the given query into sub queries 
def decompose_query_node(state: AgenticRAGState) -> dict:
    prompt_template = ChatPromptTemplate.from_messages([
        (
            "system",
            "You are a query decomposition assistant. Break the user's question into focused, "
            "self-contained sub-queries — one per retrieval step. Each sub-query should target "
            "a single distinct piece of information."
        ),
        ("human", "{query}"),
    ])
    
    chain = prompt_template | llm.with_structured_output(DecompositionDecision)
    result = chain.invoke({"query": state["query"]})
    
    formatted = "\n".join(f"Step {i+1}: {q}" for i, q in enumerate(result.sub_queries))
    
    return {"query": formatted}

#=========4th NODE ======
# 7.a structure output schema for the routing decision for llm
class RouteDecision(BaseModel):
    need_retrieval:bool
    
# 7.b route_question node - it classifies whether the query needs documents for retrieval or not.
def route_question_node(state:AgenticRAGState) -> dict:
    
    prompt_template = ChatPromptTemplate.from_messages([
        ("system", "Classify whether the following question requires retrieving information from a specialized document or the web, or can be answered from your own general knowledge."),
        ("human", "Question:{query}")
    ])
    # Convert LLM into a structured classifier that outputs a boolean decision
    chain = prompt_template | llm.with_structured_output(RouteDecision)
    decision = chain.invoke({"query":state["query"]})
    # print(decision.model_dump_json(indent=2))
    
    # Store routing decision in shared graph state
    return {"needs_retrieval":decision.need_retrieval} 

AGENT_SYSTEM_PROMPT = (
    "You are a retrieval agent with access to two tools:\n\n"
    "1. vector_store_search — use this for questions that can be answered from the internal document: "
    "a technical report titled 'Will EVs Dampen the Oil Price Shock?' covering EV adoption trajectories, "
    "oil demand displacement scenarios, fleet turnover dynamics, battery cost trends, OPEC+ supply behavior, "
    "and energy price volatility projections through 2050. "
    "Use this tool whenever the query references the report, its findings, its projections, or any topic "
    "that would plausibly appear in a domain-specific EV/oil-market research document. "
    "You may increase k beyond the default if broader coverage of the document is needed.\n\n"
    "2. web_search — use this for current or real-time information not covered by the document, such as "
    "recent market data, news, or statistics from 2024 onward. "
    "Always rephrase the query into a concise, keyword-optimized web search string before calling this tool.\n\n"
    "You may call one tool, both tools, or no tool depending on what the query requires. "
    "When both document knowledge and current data are relevant, call both tools.\n\n"
    "When the query contains numbered steps (e.g. Step 1: ..., Step 2: ...), each step is a separate "
    "retrieval sub-task. Make sure every step receives at least one retrieval call — do not skip or "
    "overlook any step. For each step, choose whichever tool or combination of tools best fits the "
    "information need; the retrieval path for each step is yours to decide."
)


#======3rd NODE======
# 8.agent node — decides which tool(s) to call based on the query | Think → Decide → Possibly call tools
def agent_node(state: AgenticRAGState) -> dict:
    #Use re-written query if available to start a fresh retrieval cycle
    rewritten = state.get("rewritten_query")
    
    if rewritten:
        messages = [
            SystemMessage(content=AGENT_SYSTEM_PROMPT),
            HumanMessage(content=rewritten)
        ]
    else:
        messages = state["messages"]
        if not messages:
            messages = [
                SystemMessage(content=AGENT_SYSTEM_PROMPT),
                HumanMessage(content=state["query"])
            ]
    response = agent_llm_with_tools.invoke(messages)
    return {"messages": [response]}
