import os
import operator
from pathlib import Path
from typing import Annotated, Literal
from pydantic import BaseModel
from tavily import TavilyClient
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_core.documents import Document
from langgraph.graph import StateGraph, START, END, MessagesState
from langgraph.prebuilt import ToolNode
from dotenv import load_dotenv
load_dotenv()

base_dir = Path(__file__).resolve().parent
documents_dir = base_dir / "documents"
pdf_path = documents_dir / "evs_oil_price_shock.pdf"

# 1. Load the PDF
loader = PyPDFLoader(str(pdf_path))
docs = loader.load()
print(f"Loaded {len(docs)} pages from the PDF.")

# 2. Split documents into chunks
splitter = RecursiveCharacterTextSplitter(chunk_size=900,chunk_overlap=150)
chunks = splitter.split_documents(docs)
print(f"\nSplit into {len(chunks)} chunks.")

# 3. Embeddings & Vector Store
embedding = OpenAIEmbeddings(model="text-embedding-3-large")
vector_store = Chroma(
    collection_name="rag_tool_use",
    embedding_function=embedding,
)
vector_store.add_documents(documents=chunks)
print("\nVector store created successfully.")

# 4. initializing model
llm = ChatOpenAI(model="gpt-5-mini",temperature=0)
agent_llm = ChatOpenAI(model="gpt-4o-mini")

# 6. State Graph definition - shared memory of the graph.
class AgenticRAGState(MessagesState):
    query:str                       # The user's original query
    retrieved_docs: list[Document]  # All documents returned from tools before filtering eg. [doc1,doc2,doc3,doc4]
    relevant_docs: list[Document]   # Documents after filtering eg.[doc1,doc2]
    context:str                     # Combined text from relevant_docs used for answer generation
    generation:str                  # Final answer generated by the LLM
    needs_retrieval:bool            # Whether retrieval is needed
    retrieval_count: int            # Number of retrieval rounds already executed
    max_retrieval_steps: int        # Maximum retrieval attempts allowed
    is_relevant:bool                # Whether documents are relevant to the query
    rewritten_query: str            # Rewritten query for better retrieval
    rewrite_count:int               # Number of query rewrites performed
    needs_decomposition: bool       # Whether query needs to be decomposed
    
    
# ----------------1st TOOL -----------------
# Register this function as a tool and return both text and raw documents
@tool(response_format="content_and_artifact") # content  → text for LLM, artifact → raw objects for workflow
def vector_store_search(query:str,k:int=3):
    """Search the vector store for relevant document passages.
    Adjust k (default 3) to retrieve more or fewer passages."""
    
    # Search vector database and return top-k matching chunks
    retriever = vector_store.as_retriever(search_type = "similarity",search_kwargs={"k":k})
    docs = retriever.invoke(query) # Perform Search | # Retrieve the most relevant document chunks for the query
    
    # Merge retrieved chunks into a single text context for the LLM
    context = "\n\n## Vector Store Results\n\n" + "\n\n".join([d.page_content for d in docs]) # merge into one context string for llm
    return context,docs # return text as content for LLM and raw docs as artifacts

    
# ----------------2nd TOOL -----------------
# Registers the function as an LLM-callable tool. Also tells LangChain Return (content, artifact) instead of just text
@tool(response_format="content_and_artifact")
def web_search(query:str, max_results:int=3):
    """Search the web for current or real-time information.
    Adjust max_results (default 3) to control how many results are returned."""
    
    client = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])
    response = client.search(query=query,max_results=max_results)
    
    # Convert Tavily search results into LangChain Document objects and vector search tool returns so web tool should return the same format
    docs = [
        Document(
            page_content= r["content"],
            metadata = {"source": r["url"],"title":r.get("title","")}
        )
        for r in response.get("results",[])
    ]
    content = "\n\n## web Search Results\n\n" + "\n\n".join([d.page_content for d in docs])
    return content,docs

# 7.Register all available tools that the agent can use
tools = [vector_store_search,web_search]
agent_llm_with_tools = agent_llm.bind_tools(tools) # LLM + Tools = Tool-Calling Agent
#======1st NODE ( LangGraph execution node)======
# 8.a tool_node — Executes tool calls generated by the LLM and returns ToolMessage outputs
tool_node = ToolNode(tools) # a node that can execute any of the defined tools

#============2nd NODE ======
class DecompositionDecision(BaseModel):
    needs_decomposition: bool
    sub_queries: list[str]  # empty list when needs_decomposition=False

# check_decomposition_node - 
def check_decomposition_node(state: AgenticRAGState) -> dict:
    prompt_template = ChatPromptTemplate.from_messages([
        (
            "system",
            "You are a query analysis assistant. Determine if the user's question asks for "
            "multiple distinct pieces of information that each require separate retrieval. "
            "If yes, needs_decomposition should be True. "
            "If the question is simple or self-contained, needs_decomposition should be False."
        ),
        ("human", "{query}"),
    ])
    
    chain = prompt_template | llm.with_structured_output(DecompositionDecision)
    result = chain.invoke({"query": state["query"]})
    
    return {"needs_decomposition": result.needs_decomposition}


#===========3rd NODE ======
#9.decompose_query_node - it decomposes the given query into sub queries 
def decompose_query_node(state: AgenticRAGState) -> dict:
    prompt_template = ChatPromptTemplate.from_messages([
        (
            "system",
            "You are a query decomposition assistant. Break the user's question into focused, "
            "self-contained sub-queries — one per retrieval step. Each sub-query should target "
            "a single distinct piece of information."
        ),
        ("human", "{query}"),
    ])
    
    chain = prompt_template | llm.with_structured_output(DecompositionDecision)
    result = chain.invoke({"query": state["query"]})
    
    formatted = "\n".join(f"Step {i+1}: {q}" for i, q in enumerate(result.sub_queries))
    
    return {"query": formatted}

#=========4th NODE ======
# 10.a structure output schema for the routing decision for llm
class RouteDecision(BaseModel):
    need_retrieval:bool
    
# 10.b route_question node - it classifies whether the query needs documents for retrieval or not.
def route_question_node(state:AgenticRAGState) -> dict:
    
    prompt_template = ChatPromptTemplate.from_messages([
        ("system", "Classify whether the following question requires retrieving information from a specialized document or the web, or can be answered from your own general knowledge."),
        ("human", "Question:{query}")
    ])
    # Convert LLM into a structured classifier that outputs a boolean decision
    chain = prompt_template | llm.with_structured_output(RouteDecision)
    decision = chain.invoke({"query":state["query"]})
    # print(decision.model_dump_json(indent=2))
    
    # Store routing decision in shared graph state
    return {"needs_retrieval":decision.need_retrieval} 

AGENT_SYSTEM_PROMPT = (
    "You are a retrieval agent with access to two tools:\n\n"
    "1. vector_store_search — use this for questions that can be answered from the internal document: "
    "a technical report titled 'Will EVs Dampen the Oil Price Shock?' covering EV adoption trajectories, "
    "oil demand displacement scenarios, fleet turnover dynamics, battery cost trends, OPEC+ supply behavior, "
    "and energy price volatility projections through 2050. "
    "Use this tool whenever the query references the report, its findings, its projections, or any topic "
    "that would plausibly appear in a domain-specific EV/oil-market research document. "
    "You may increase k beyond the default if broader coverage of the document is needed.\n\n"
    "2. web_search — use this for current or real-time information not covered by the document, such as "
    "recent market data, news, or statistics from 2024 onward. "
    "Always rephrase the query into a concise, keyword-optimized web search string before calling this tool.\n\n"
    "You may call one tool, both tools, or no tool depending on what the query requires. "
    "When both document knowledge and current data are relevant, call both tools.\n\n"
    "When the query contains numbered steps (e.g. Step 1: ..., Step 2: ...), each step is a separate "
    "retrieval sub-task. Make sure every step receives at least one retrieval call — do not skip or "
    "overlook any step. For each step, choose whichever tool or combination of tools best fits the "
    "information need; the retrieval path for each step is yours to decide."
)


#======5th NODE======
# 11.agent node — decides which tool(s) to call based on the query | Think → Decide → Possibly call tools
def agent_node(state: AgenticRAGState) -> dict:
    #Use re-written query if available to start a fresh retrieval cycle
    rewritten = state.get("rewritten_query")
    
    if rewritten:
        messages = [
            SystemMessage(content=AGENT_SYSTEM_PROMPT),
            HumanMessage(content=rewritten)
        ]
    else: 
        messages = state["messages"]
        if not messages:
            messages = [
                SystemMessage(content=AGENT_SYSTEM_PROMPT),
                HumanMessage(content=state["query"])
            ]
    response = agent_llm_with_tools.invoke(messages)
    return {"messages": [response]}

#======6th NODE======
# 12.collect_tool_output node — drains ToolMessages into state fields | Take tool results → extract useful data → store in state
def collect_tool_output_node(state: AgenticRAGState) -> dict:
    all_docs = []
    # Iterate through the last message from the state backwards, until finding HumanMessage
    for msg in reversed(state["messages"]):
        if isinstance(msg, HumanMessage):
            break
        # Iterate through tool outputs and extract raw Document objects
        if isinstance(msg, ToolMessage):
            all_docs.extend(msg.artifact)  # Collect raw documents from tool outputs | extend - returned single combined list
    all_docs.reverse()
    return {"retrieved_docs": all_docs} # # Store all raw documents retrieved from tools


#======7th NODE======
class RelevanceEvaluation(BaseModel):
    is_relevant: bool
    
# 13.evaluate_docs_node -  it evaluate the retrieved docs and save relevant docs 
def evaluate_docs_node(state: AgenticRAGState) -> dict :
    docs = state.get("retrieved_docs") or []
    if not docs :
        return{ "is_relevant" : False, "relevant_docs":[],"context":""}
    
    active_query = state.get("rewritten_query") or state["query"]
    
    prompt_template = ChatPromptTemplate.from_messages([
        (
            "system",
            "You are a relevance evaluator. Given a user query and a single document passage, "
            "determine whether the passage contains useful information to answer the query. "
            "Return is_relevant=True only if the passage directly addresses the query with specific facts or analysis. "
            "Return is_relevant=False if it is off-topic, too vague, or does not help answer the query."
        ),
        ("human", "Query: {query}\n\nDocument passage:\n{doc}"),
    ])
    chain = prompt_template | llm.with_structured_output(RelevanceEvaluation)
    
    relevant_docs = []
    for doc in docs:
        result = chain.invoke({"query" : active_query, "doc" : doc.page_content})
        if result.is_relevant:
            relevant_docs.append(doc)
    
    is_relevant = len(relevant_docs) > 0
    context = "\n\n".join(d.page_content for d in relevant_docs )

    return { "is_relevant": is_relevant, "relevant_docs":relevant_docs,"context":context}

#======8th NODE======
# 14.rewrite_query_node  - it rewrite the query if no relevant docs found 
def rewrite_query_node(state: AgenticRAGState) -> dict :
    count = state.get("retrieval_count", 0)
    
    prompt_template = ChatPromptTemplate.from_messages([
        ( "system",
            "You are a query rewriting assistant. A retrieval system searched for information to answer the user's "
            "query but none of the retrieved documents were relevant. Your task is to rewrite the query to be more "
            "specific, use different terminology, or focus on a narrower aspect that is more likely to match "
            "content in the knowledge source. Return only the rewritten query string."),
        ("human", "Original query: {query}\n\nRewritten query:"),
    ])
    chain = prompt_template | llm
    response = chain.invoke({"query": state["query"]})
    new_query = response.content.strip()

    return {"rewritten_query": new_query, "rewrite_count": count + 1}


#======9th NODE======
# 15. generate_node
def generate_node(state:AgenticRAGState) ->dict:
    # No answer fallback when all rewrite attempts are existed with no relevant docs.
    if state.get("rewrite_count",0)>= 3 and not state.get("is_relevant"):
        return{
            "generation":(
                "I was unable to find the relevant information to answer your query after multiple retribble attempts."
                "The knowledge source does not appear to contain content that addresses this question."
            )
        }
    
    query = state["query"]
    context = state.get("context") or ""
    
    if context:
        prompt_template = ChatPromptTemplate.from_messages([
            ("system", "Answer the question using only the context below.\n\nContext:\n{context}"),
            ("human", "{query}"),
        ])
        response = (prompt_template | llm).invoke({"context":context, "query":query})
    else:
        prompt_template = ChatPromptTemplate.from_messages([
            ("system", "Answer the following question from your general knowledge."),
            ("human", "Query: {query}"),
        ])
        response = (prompt_template | llm).invoke({"query":query})
    return {"generation":response.content}

#======10th NODE======
# 16. check_retrieval_limit node — increments the retrieval counter after each tool round
def check_retrieval_limit_node(state: AgenticRAGState) -> dict:
    count = state.get("retrieval_count", 0)
    
    return {"retrieval_count": count + 1}

# ==============================
# ROUTING FUNCTIONS
# ==============================
        
# ======= 17. The conditional ROUTER (routing function) =====   
def route_after_classification(state: AgenticRAGState)->Literal["check_decomposition_node","generate_node"]:
     # Decide whether to use agent tools or go directly to final generation
    return "check_decomposition_node" if state["needs_retrieval"] else "generate_node"

def route_after_decomposition_check(state: AgenticRAGState) -> Literal["decompose_query_node", "agent_node"]:
    return "decompose_query_node" if state["needs_decomposition"] else "agent_node"

def route_after_agent(state:AgenticRAGState) -> Literal["tool_node","collect_tool_output_node"]:
    return "tool_node" if state["messages"][-1].tool_calls else "collect_tool_output_node"
    # If tool calls exist → execute tool; otherwise → process results

# Decide whether the agent gets another tool-calling round, or is forced to stop
def route_after_limit_check(state: AgenticRAGState) -> Literal["agent_node", "collect_tool_output_node"]:
    return "collect_tool_output_node" if state["retrieval_count"] >= state["max_retrieval_steps"] else "agent_node"

def route_after_evaluation(state: AgenticRAGState) -> Literal["generate_node","rewrite_query_node" ]:
    return "generate_node" if state["is_relevant"] else "rewrite_query_node"

def route_after_rewrite(state: AgenticRAGState)-> Literal["agent_node", "generate_node"]:
    return "generate_node" if state.get("rewrite_count", 0) >= 3 else "agent_node"




# 18. Graph defination
g = StateGraph(AgenticRAGState)
g.add_node("tool_node",tool_node)
g.add_node("check_decomposition_node",check_decomposition_node)
g.add_node("decompose_query_node",decompose_query_node)
g.add_node("route_question_node",route_question_node)
g.add_node("agent_node",agent_node)
g.add_node("collect_tool_output_node",collect_tool_output_node)
g.add_node("evaluate_docs_node",evaluate_docs_node)
g.add_node("rewrite_query_node",rewrite_query_node)
g.add_node("generate_node",generate_node)
g.add_node("check_retrieval_limit_node",check_retrieval_limit_node)

# 19. edges
g.add_edge(START,"route_question_node")
g.add_conditional_edges("route_question_node",route_after_classification)
g.add_conditional_edges("check_decomposition_node",route_after_decomposition_check)
g.add_edge("decompose_query_node","agent_node")
g.add_conditional_edges("agent_node", route_after_agent)
g.add_edge("tool_node","check_retrieval_limit_node")
g.add_conditional_edges("check_retrieval_limit_node",route_after_limit_check)
g.add_edge("collect_tool_output_node","evaluate_docs_node")
g.add_conditional_edges("evaluate_docs_node",route_after_evaluation)
g.add_conditional_edges("rewrite_query_node",route_after_rewrite)
g.add_edge("generate_node",END)

graph = g.compile()
save_path = base_dir / "agentic_rag_step06.png"
png_data = graph.get_graph().draw_mermaid_png()
with open(save_path, "wb") as f:
    f.write(png_data)
print("Graph saved successfully!")


# Case 1: simple query — expect no decomposition, query unchanged
query_1 = (
    "According to the report, by how many million barrels per day could a 300-million EV fleet "
    "displace oil demand by 2030?"
)

result_1 = graph.invoke({
    "query": query_1,
    "messages": [],
    "retrieved_docs": [],
    "relevant_docs": [],
    "context": "",
    "retrieval_count": 0,
    "max_retrieval_steps": 3,
    "rewrite_count": 0,
    "rewritten_query": "",
})

print("\nQUERY:",query_1)
print("=== Case 1: Simple query — no decomposition ===")
print("Final query:", result_1.get("query"))
print("Is relevant:", result_1.get("is_relevant"))
print("Relevant docs count:", len(result_1.get("relevant_docs") or []))
print("\nGeneration:\n", result_1.get("generation"))



# Case 2: complex multi-part query — expect decomposition into numbered steps

query_2 = (
    "Impact of EVs on the oil industry, "
    "and what is the current price of oil in US dollars for Brent Crude"
)

result_2 = graph.invoke({
    "query": query_2,
    "messages": [],
    "retrieved_docs": [],
    "relevant_docs": [],
    "context": "",
    "retrieval_count": 0,
    "max_retrieval_steps": 10,
    "rewrite_count": 0,
    "rewritten_query": "",
})
print("\nQUERY:",query_2)
print("=== Case 2: Complex query — decomposition expected ===")
print("Final query (after decomposition):\n", result_2.get("query"))
print("\nIs relevant:", result_2.get("is_relevant"))
print("Relevant docs count:", len(result_2.get("relevant_docs") or []))
print("Retrieval count:", result_2.get("retrieval_count"))
print("\nGeneration:\n", result_2.get("generation"))

